### PR TITLE
Refactoring switch statements [WIP/feedback requested]

### PR DESCRIPTION
**Pull request by ashleybaldock**
Suggestion for replacement of switch statements (could go further and merge tileSources to have one config object).

Needs testing/tidying, but wanted to check if this is a welcome direction first :)

### CODE REVIEW

**Comment by ashleybaldock** [comment]
Oh, well if you're going with React it'll be completely different - I can probably help with that though (and you might find useful components/styling stuff in the [wand sim repo.](https://github.com/ashleybaldock/noita-wand-simulator)  :)

**Comment by Freshtopia** [comment]
Looks good to me for now! The react overhaul will take a bit anyways so having a cleaner codebase is always a plus in the mean time. Also would love the help on reactifying this whole thing @ashleybaldock ! Main thing we would have to overcome is the whole site is hosted through the Hugo CMS platform so it may be a bit weird, but please feel free to send me a DM on twitch so we can connect and take a look into some stuff if you'd like to help!

**Review by Freshtopia — APPROVED** [review]
Code is clean and efficient, and I'm very happy to get away from the switch statements! Great work!

**Review by Freshtopia — APPROVED** [review]

**Comment by Freshtopia** [comment]
@ashleybaldock since there were some major changes to the project while you were working on this your file is out of sync. Would you please

**Pull request closed without merging**
